const minds = [
    {   
        "id": 1,
        "src": "ali",
        "name": "Ali Arsanjani, PhD", 
        "position": "Director | ex-AWS WW Tech Leader & Chief Principal AI/ML| ex-CTO IBM | VP AI/ML",
        "country": "US", 
        "company": "Google",
    },
    {   
        "id": 2,
        "src": "noel",
        "name": "Noelle Silver", 
        "position": "Partner, AI & Analytics at IBM | Microsoft MVP in AI",
        "country": "US", 
        "company": "IBM",
    },
    {   
        "id": 3,
        "src": "johanas",
        "country": "US",
        "name": "Johannes Castner", 
        "position": "Venture Partner at Post Urban. Founder at CollectiWise. TEDx speaker", 
        "company": "Post Urban",
    },
    {   
        "id": 4,
        "src": "carl",
        "country": "MX",
        "name": "Carl Handlin", 
        "position": "Head of Data Science & Artificial Intelligence", 
        "company": "Rappi",
    },
    {   
        "id": 5,
        "src": "leon",
        "country": "MX",
        "name": "León Palafox", 
        "position": "Head of Artificial Intelligence, Retail, Telco and Media", 
        "company": "GRUPO SALINAS",
    },
    {   
        "id": 6,
        "src": "maria",
        "country": "MX",
        "name": "MARIA CRUZ", 
        "position": "Head of Data Science", 
        "company": "THE WALT DISNEY LATAM",
    },
    {   
        "id": 7,
        "src": "",
        "country": "MX",
        "name": "ELIANA CANTON", 
        "position": "Head of Data Science", 
        "company": "THE WALT DISNEY LATAM",
    },
    {   
        "id": 8,
        "src": "david",
        "name": "David Colwell", 
        "country": "AU",
        "position": "VP - Artificial Intelligence and Machine Learning", 
        "company": "Tricentis",
    },
    {   
        "id": 9,
        "src": "muni",
        "country": "ID",
        "name": "Muni Vinay Kamisetty", 
        "position": "Head of Data and Automation - Enterprise Tech", 
        "company": "Lazada",
    },
    {   
        "id": 10,
        "src": "aravin",
        "country": "IN",
        "name": "Aravind Ganapathiraju", 
        "position": "VP, Applied AI", 
        "company": "Uniphore",
    },
    {   
        "id": 11,
        "src": "nam_ma",
        "country": "VN",
        "name": "Nam Ma", 
        "position": "Head of AI labs", 
        "company": "VNG",
    },
    
];

export default minds;
